<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="1" hostname="WKSN-063" id="0" name="FooterTest" package="com.angloinfo.tests" tests="5" time="140.512" timestamp="21 Nov 2014 10:35:54 GMT">
      <testcase classname="com.angloinfo.tests.FooterTest" name="testDirectoryRedirection" time="28.416" />

      <testcase classname="com.angloinfo.tests.FooterTest" name="testDiscussionRedirection" time="31.849">
          <failure message="can not find P(C:\\Users\\stephb\\workspace\\AngloInfoTesting\\expectedImg\\discussions.png) S: 0.7 on the screen." type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: can not find P(C:\\Users\\stephb\\workspace\\AngloInfoTesting\\expectedImg\\discussions.png) S: 0.7 on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at com.angloinfo.util.Utility.isImgInScreen(Utility.java:442)
	at com.angloinfo.fixtures.Footer.isPageDisplayed(Footer.java:219)
	at com.angloinfo.fixtures.Footer.isDiscussionsDisplayed(Footer.java:150)
	at com.angloinfo.tests.FooterTest.testDiscussionRedirection(FooterTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>

      </testcase>
 <!-- testDiscussionRedirection -->
      <testcase classname="com.angloinfo.tests.FooterTest" name="testScrolling" time="21.139" />

      <testcase classname="com.angloinfo.tests.FooterTest" name="testGuidesRedirection" time="30.689" />

      <testcase classname="com.angloinfo.tests.FooterTest" name="testWhatsOnRedirection" time="28.419" />

  </testsuite>
</testsuites>
